version: "3.8"
services:
  api:
    build:
      context: ..
      dockerfile: plataforma_pbl/_ops/Dockerfile.backend
    env_file:
      - ../plataforma_pbl/fastapi_backend/.env
    ports:
      - "8000:8000"
  web:
    build:
      context: ..
      dockerfile: plataforma_pbl/_ops/Dockerfile.frontend
    environment:
      - VITE_API_URL=http://api:8000
    ports:
      - "5173:80"
    depends_on:
      - api
